### ISSUE TITLE
Error during News Query search

### ISSUE THREAD

**Issue by gogasca** [gogasca/news_ml#10]
```
Traceback (most recent call last):
  File "/Users/gogasca/Documents/Development/dpe/venv/newsml_venv/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/gogasca/Documents/Development/dpe/venv/newsml_venv/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/gogasca/Documents/Development/dpe/news/main/common/TornadoBacklog.py", line 70, in wrapped
    return function(*args, **kwargs)
  File "/Users/gogasca/Documents/Development/dpe/news/main/common/TornadoBacklog.py", line 181, in handle_request
    news_processor.process_articles(articles, news_provider, self.campaign)
  File "/Users/gogasca/Documents/Development/dpe/news/main/lib/news_api/top_news_processor.py", line 97, in process_articles
    article.content or article.description)
  File "/Users/gogasca/Documents/Development/dpe/news/services/nlp/utils.py", line 212, in get_sentiment_scores
    sentiment_anaysis_result = nlp.analyze_sentiment(text)
  File "/Users/gogasca/Documents/Development/dpe/news/services/nlp/nlp.py", line 81, in analyze_sentiment
    response = request.execute()
  File "/Users/gogasca/Documents/Development/dpe/venv/newsml_venv/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/gogasca/Documents/Development/dpe/venv/newsml_venv/lib/python3.6/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://language.googleapis.com/v1/documents:analyzeSentiment?alt=json returned "The language nl is not supported for document_sentiment analysis.">
```

**Comment by gogasca** [comment]
Fixed. Handle error and print it
