### ISSUE TITLE
Campaign error

### ISSUE THREAD

**Issue by gogasca** [gogasca/news_ml#12]
```
,reason='OK',request=<tornado.httpclient.HTTPRequest object at 0x7f763412ffd0>,request_time=1.084010124206543,time_info={}))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/src/news_ml/main/common/TornadoBacklog.py", line 70, in wrapped
    return function(*args, **kwargs)
  File "/usr/local/src/news_ml/main/common/TornadoBacklog.py", line 178, in handle_request
    articles = news_handler.handle_http_response(response.body)
  File "/usr/local/src/news_ml/main/lib/news_api/top_news_handler.py", line 39, in handle_http_response
    json_response = json.loads(response)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by gogasca** [comment]
Issue to be fixed once we add support to Python 3.5, Python 3.7. Currently Python 3.6 is required.
